### ISSUE TITLE
yml multi-file orientend API Proxy configuration

### ISSUE THREAD

**Issue by gigioSouza** [gigioSouza/japigee-bundler#19]
After start the development of swagger/oas extensions interpreter for creating API Proxies, I quickly saw that it'd be a burden to deal gigantic specification by adding a second context(configure API Proxies) to it.

Won't drop that idea, but for my short/medium term needs, a yml multi-file oriented approach is a wiser choice.

Ideally the swagger/oas will still be used, but as an optional reference to the main configuration file.

## API Proxy mainc configuration file

Used as an API Manifest to declare the whole API, can have all the configuration as well as
reference other files to do so.

```yml
# apiproxy.yml

api:
  name: string
  displayName: string -- optional, default value is name prop
  description: string -- optional
  revision: integer
  configurationVersion: -- optional, default value is already 4 and 0
    major: 4
    minor: 0
  spec: string -- path|url to OAS 3.*
  targetServers: -- optional, if no target server is used
    - string
  kvms: -- optional, if no kvm is used
    - string
  caches: -- optional, if no cache is used
    - string
  sharedFlows: -- optional, if no shared flow is used
    - string

proxies: ProxyEndpoint | ProxyEndpoint array | string | string array
targets: TargetEndpoint | TargetEndpoint array | string | string array
policies: Policy array | string | string array
```

---

### ProxyEndpoint 
```yml
name: string -- optional when there is only one, default value is 'default'
preFlow: Flow -- optional
postFlow: Flow -- optional
postClientFlow: Flow-- optional
faultRules: FaultRule array -- optional
defaultFaultRule: FaultRule -- optional
flows: Flow array -- optional
proxyConn:
  basepath: string
  virtualHosts: string | string array -- optional, default value is 'default'
  properties: key/value map -- optional
routeRules: RouteRule
```

### Flow
```yml
specId: string -- only available for 'flows' configuration
name: string
description: string -- optional
condition: string -- optional
request:
  - name: string
    condition: string -- optional
response:
  - name: string
    condition: string -- optional
```

When using in `preFlow`, `name` is optional and default value is 'PreFlow'.  
When using in `postFlow`, `name` is optional and default value is 'PostFlow'.  
When using in `postClientFlow`, `name` is optional and default value is 'PostFlow' and the `request` attribute is discarded.  

`specId` must be used within a spec. It'll pre-configure the flow instance with the corresponding`operationId` in the `api.spec`.

Example:
```yml
# apiproxy.yml
api:
  spec: ./oas.yml

proxies:
  - flows:
      - specId: get-user-by-id
```
```yml
openapi: 3.0.3
paths:
  /users/{id}:
    get:
      operationId: get-user-by-id
      description: Retrieve the user from the given id
```
Generated xml
```xml
<ProxyEndpoint>
  <Flows>
    <Flow name="get-user-by-id">
      <Description>Retrieve the user from the given id</Description>
      <Condition>(proxy.pathsuffix JavaRegex "/users/([^\/]+)(/?)") and (request.verb = "GET")</Condition>
    </Flow>
  </Flows>
</ProxyEndpoint>
```

### FaultRule
```yml
name: string
condition: string -- optional
steps:
  - name: string
    condition: string -- optional
```

### RouteRule
```yml
name: string -- optional when there is only one, default value is 'default'
url: string
target: string
condition: string -- optional 
```
One of `url` or `target` are required.

### Policy
```yml
name: string
displayName: string -- optional, default value is name prop
type: string
async: boolean -- optional, default value is 'false'
continueOnError: boolean -- optional, default value is 'false'
enabled: boolean -- optional, default value is 'true'
properties: key/value map
configuration: object 
```
`type` is the policy xml name, as specified in the [docs](https://docs.apigee.com/api-platform/reference/policies/reference-overview-policy).
`configuration` is where you configure your policy using the [docs reference](https://docs.apigee.com/api-platform/reference/policies/reference-overview-policy). All attribute names should use **camelCase**.
