### ISSUE TITLE
Add yaml lib and map apiproxy model

### ISSUE THREAD

**Issue by gigioSouza** [gigioSouza/japigee-bundler#21]
Add yaml lib and map apiproxy model from #19

```yml
# apiproxy.yml

apiproxy:
  name: string
  displayName: string # optional, default value is name prop
  description: string # optional
  revision: integer
  configurationVersion: # optional, default value is already 4 and 0
    major: 4
    minor: 0

proxies: string | string array
targets: string | string array
policies: string | string array

spec: string # path|url to OAS 3.*

targetServers: # optional, if no target server is used
  - string

kvms: # optional, if no kvm is used
  - string

caches: # optional, if no cache is used
  - string

sharedFlows: # optional, if no shared flow is used
  - string
```
