### ISSUE TITLE
Add apigee extensions to Swagger

### ISSUE THREAD

**Issue by gigioSouza** [gigioSouza/japigee-bundler#8]
Add apigee extensions to Swagger

**Comment by gigioSouza** [comment]
`x-japigee` example model:
```yml
components:
  x-japigee:
    proxy:
      - name: string
        basepath: string
        virtualhosts:
          - string
        routerules:
          - name: string
            condition: string
        faultRules:
          - name: string
            condition: string
            steps:
              - name: string
                condition: string
        defaultFaultRules:
            name: string
            condition: string
            steps:
              - name: string
                condition: string
        preFlow:
          name: string
          description: string
          request:
            - name: string
              condition: string
          response:
            - name: string
              condition: string
        postFlow:
          name: string
          description: string
          request:
            - name: string
              condition: string
          response:
            - name: string
              condition: string
        postClientFlow:
          name: string
          description: string
          response:
            - name: string
              description: string
              condition: string
    target:
      - name: string
        http:
          url: string
          path: string
          loadbalancer:
            algorithm: string
            servers:
              - string
          sslInfo:
            enabled: boolean
            clientAuthEnabled: boolean
            keyStore: string
            keyAlias: string
            trustStore: string
            cyphers:
              - string
            protocol:
              - string
          properties:
            - name: string
              value: string
        local:
          apiProxy: string
          proxyEndpoint: string
          path: string
        script:
          resourceUrl: string
          environmentVariables:
            - name: string
              value: string
          arguments:
            - string
        faultRules:
          - name: string
            condition: string
            steps:
              - name: string
                condition: string
        defaultFaultRules:
            name: string
            condition: string
            steps:
              - name: string
                condition: string
        preFlow:
          name: string
          description: string
          request:
            - name: string
              condition: string
          response:
            - name: string
              condition: string
        postFlow:
          name: string
          description: string
          request:
            - name: string
              condition: string
          response:
            - name: string
              condition: string
```

**Comment by gigioSouza** [comment]
`x-japigee` example for `PathItems`:
```yml
paths:
  /endpoint:
    get:
      x-japigee:
        name: string -- override operationId
        description: string -- override description
        request:
          - name: string
            condition: string
        response:
          - name: string
            condition: string
```
